### ISSUE TITLE
When will you share your code? Thanks.

### ISSUE THREAD

**Issue by ducanhnguyen-lab** [czczup/ViT-Adapter#1]
Appreciate your work.

**Comment by czczup** [comment]
> Appreciate your work.

Hi, code will be released around June 2022.

**Comment by chumingqian** [comment]
Waiting  for  it

**Comment by Omar4Robotics** [comment]
Is cnn dead?

**Comment by mitming** [comment]
> Is cnn dead?

No.

**Comment by czczup** [comment]
Code and models have been released.
