### ISSUE TITLE
分割部分，请问背景算在类别里面嘛？

### ISSUE THREAD

**Issue by 847001315** [czczup/ViT-Adapter#10]
num_things_classes = 8
num_stuff_classes = 11
num_classes = num_things_classes + num_stuff_classes
【城市景观的config】
这里面包括背景嘛？

**Comment by czczup** [comment]
> num_things_classes = 8 num_stuff_classes = 11 num_classes = num_things_classes + num_stuff_classes 【城市景观的config】 这里面包括背景嘛？

cityscapes的19类不包含背景

**Comment by 847001315** [comment]
那请问，背景类的mask像素值是多少？ 0？还是255？

**Comment by 847001315** [comment]
谢谢您及时回复，非常感谢！！
