### ISSUE TITLE
Installation problems in google colab.

### ISSUE THREAD

**Issue by ThomasBaumgartner1** [czczup/ViT-Adapter#103]
When i'm trying to install all the required torch and mmcv frameworks, i suppose i'm getting in trouble with dependencies. On the colab there is python 3.10.11 installed and i'm trying to install all the frameworks as given. Are there any updated recommendations of the required torch/mmcv versions? 

I already couldnt install torch1.9.0+cu111, had to change it to torch1.11.0+cu113 which worked for me to install. 
But now it gets stuck with the !pip install mmcv-full==1.4.2 installation.

**Comment by ThomasBaumgartner1** [comment]
the output of the first cell

# Check nvcc version
!nvcc -V
# Check GCC version
!gcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by IamShubhamGupto** [comment]
@ThomasBaumgartner1 
Hey I was playing around with the notebook and PyTorch versions and it seems like PyTorch 1.9 does not support python 3.10 (not sure when they will be adding support)

for that reason, I have bumped the PyTorch version to 1.11 and it seems to work now. The colab has been updated too, you can find it [here](https://colab.research.google.com/drive/1yEd5lQMjShloicImtShkwttb74KPGY5U?usp=sharing)
