### ISSUE TITLE
May I ask if there are ViT-Adapter and BEiTAdapter in the network trained in Cityscapes, is there any difference?

### ISSUE THREAD

**Issue by huanruizhang123** [czczup/ViT-Adapter#104]
![image](https://github.com/czczup/ViT-Adapter/assets/124413465/a5212e0f-35b8-4566-a1f1-bd7c40574a05)

**Comment by czczup** [comment]
Hi, I only trained BEiTAdapter using BEiT pre-trained weights on Cityscapes. The network architecture of `ViTAdapter` and `BEiTAdapter` are the same, except BEiT uses relative position encoding.
