### ISSUE TITLE
ModuleNotFoundError: No module named 'mmengine'

### ISSUE THREAD

**Issue by pkbeen** [czczup/ViT-Adapter#105]
Hello, I am a student who is studying while using github.
I tried to train custom dataset.
Previously I met the problem "no module named "ops.modules". So I resolved other issues by add export PYTHONPATH=/path ~~

But I met the problem ModuleNotFoundError: No module named 'mmengine'.

Can you help me??

![Screenshot from 2023-06-19 17-39-05](https://github.com/czczup/ViT-Adapter/assets/83258894/ce6dffe4-42d9-416f-8c2f-59a5620058aa)

**Comment by czczup** [comment]
Our current version does not use mmengine. This prompt indicates that the version of mmseg installed is too new.
