### ISSUE TITLE
pretrained = 'https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_large_patch16_224_pt22k_ft22k.pth'

### ISSUE THREAD

**Issue by CcccccaptionOvO** [czczup/ViT-Adapter#106]
can not download

**Comment by czczup** [comment]
https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_large_patch16_224_pt22k_ft22k.pth?sv=2021-10-04&st=2023-06-08T11%3A16%3A02Z&se=2033-06-09T11%3A16%3A00Z&sr=c&sp=r&sig=N4pfCVmSeq4L4tS8QbrFVsX6f6q844eft8xSuXdxU48%3D

**Comment by czczup** [comment]
<img width="1006" alt="image" src="https://github.com/czczup/ViT-Adapter/assets/23737120/ec6d2656-c31e-4876-8ee4-868f602666ca">
https://github.com/microsoft/unilm/tree/master/beit

You can download it from here.
