### ISSUE TITLE
我想将pathszie改成14，除了在配置文件中修改之外，还需要修改代码的哪里

### ISSUE THREAD

**Issue by stonewjf** [czczup/ViT-Adapter#108]

**Comment by czczup** [comment]
预训练本身的patch size就是14吗

**Comment by stonewjf** [comment]
> 预训练本身的patch size就是14吗

对，，我想把DinoV2的预训练模型接到里面

**Comment by czczup** [comment]
我新建了一个dinov2的分支，今天尝试一下接进来

**Comment by czczup** [comment]
<img width="833" alt="image" src="https://github.com/czczup/ViT-Adapter/assets/23737120/f916992a-1614-49e3-9dbb-bf1460d34020">
现在所有key已经可以对上了，精度正不正常还需要再确认一下。

**Comment by czczup** [comment]
DINOv2的readme见https://github.com/czczup/ViT-Adapter/tree/dinov2/detection/configs/mask_rcnn/dinov2

**Comment by czczup** [comment]
目前来看，DINOv2的权重必须搭配LayerDecayOptimizerConstructor使用，否则性能会有影响

**Comment by czczup** [comment]
| Backbone      | Pretrain                                                                                                                                                           | Lr schd | box AP      | mask AP     | #Param | 
|:-------------:|:-------------:|:-------:|:-----------:|:-----------:|:------:|
| ViT-S                | DeiT-S         | 3x+MS   | 44.0        | 39.9        | 42M    | 
| ViT-Adapter-S | DeiT-S         | 3x+MS   | 48.2        | 42.8        | 48M    | 
| ViT-Adapter-S | DINOv2-S   | 3x+MS   | 50.8        | 44.9        | 48M    |
