### ISSUE TITLE
Other versions of CUDA / Linux / Python

### ISSUE THREAD

**Issue by Nicolas-M15** [czczup/ViT-Adapter#109]
ViT works only with Pytorch 1.9,  CUDA 11.1, Ubuntu 10, and Python 3.7: Is that correct?

I must use ViT on an existing environment using a more recent config, and it is very difficult to run ViT on it due to libraries incompatibilities.

Does ViT work in more recent environments like Python 3.8 and CUDA 11.6? Did you test ViT in other environments?

**Comment by czczup** [comment]
I can run this code with Pytorch 1.9/1.11/1.12, CUDA 11.1/11.3/11.6, and Python 3.7/3.8.

**Comment by Nicolas-M15** [comment]
Thank you, czczup.
Is it also working with Ubuntu 22?
I had lot of install issues installing on a Docker image, because the install commands are different and there are conflicts (for instance, CUDA can't detect the GPU).

**Comment by Nicolas-M15** [comment]
I'll try and update the issue. Have you succeeded to adapt those lines in a Dockerfile?
ln -s ../detection/ops ./
cd ops & sh make.sh # compile deformable attention

**Comment by czczup** [comment]
I have successfully compiled deformable attention in docker. I used ViT-Adapter and nvidia-docker in wsdm2023 competition before.
