### ISSUE TITLE
你好，请问”assert (count_mat == 0).sum() == 0“，在文件中的作用是什么？

### ISSUE THREAD

**Issue by 847001315** [czczup/ViT-Adapter#11]
ViT-Adapter-main/segmentation/mmseg_custom/models/segmentors/encoder_decoder_mask2former.py的195行，存在句子”assert (count_mat == 0).sum() == 0“，每次运行都会因为这个异常而跳出来。我将其注释掉，程序可以正常运行，但每次得出来的结果都是一样的，不知道和这里是否有关？想请问，count_mat代表什么意思？

下面是那一段代码：
    def slide_inference(self, img, img_meta, rescale):
        """Inference by sliding-window with overlap.

        If h_crop > h_img or w_crop > w_img, the small patch will be used to
        decode without padding.
        """
        print("img.shape",img.shape)
        # print("img",img)
        h_stride, w_stride = self.test_cfg.stride
        h_crop, w_crop = self.test_cfg.crop_size
        batch_size, _, h_img, w_img = img.size()

        num_classes = self.num_classes
        # print("num_class",num_classes)

        h_grids = max(h_img - h_crop + h_stride - 1, 0) // h_stride + 1
        w_grids = max(w_img - w_crop + w_stride - 1, 0) // w_stride + 1
        preds = img.new_zeros((batch_size, num_classes, h_img, w_img))
        # print("preds",preds)
        count_mat = img.new_zeros((batch_size, 1, h_img, w_img))
        # print("count_mat",count_mat)
        for h_idx in range(h_grids):
            for w_idx in range(w_grids):
                y1 = h_idx * h_stride
                x1 = w_idx * w_stride
                y2 = min(y1 + h_crop, h_img)
                x2 = min(x1 + w_crop, w_img)
                y1 = max(y2 - h_crop, 0)
                x1 = max(x2 - w_crop, 0)
                crop_img = img[:, :, y1:y2, x1:x2]
                crop_seg_logit = self.encode_decode(crop_img, img_meta)
                preds += F.pad(crop_seg_logit,
                               (int(x1), int(preds.shape[3] - x2), int(y1),
                                int(preds.shape[2] - y2)))

                count_mat[:, :, y1:y2, x1:x2] += 1
                # print(count_mat[:, :, y1:y2, x1:x2])

        # assert (count_mat == 0).sum() == 0
        if torch.onnx.is_in_onnx_export():
            # cast count_mat to constant while exporting to ONNX
            count_mat = torch.from_numpy(
                count_mat.cpu().detach().numpy()).to(device=img.device)
        preds = preds / count_mat
        # preds = preds
        if rescale:
            preds = resize(
                preds,
                size=img_meta[0]['ori_shape'][:2],
                mode='bilinear',
                align_corners=self.align_corners,
                warning=False)
        return preds

打扰了~~~

**Comment by czczup** [comment]
你好，能提供一下具体的环境信息吗

**Comment by 847001315** [comment]
好的，以下是我的环境信息：
cuda：10.2 pytorch:1.10  mmcv-full:1.4.4 mmsegmentation:0.20.2 mmdet:2.22.0
数据集说明：为自定义的医学数据集，其中包含一类目标类，其余被背景，图像尺寸为【112*112，三通道】，mask图像为【112*112，单通道，同时处理过，将背景的像素点的像素值设为0，目标类的像素点的像素值设为1】

**Comment by czczup** [comment]
@duanduanduanyuchen

**Comment by 847001315** [comment]
> @duanduanduanyuchen 看一看config

您是叫他来看我的config吗？还是我去看他某个仓库的config？

**Comment by czczup** [comment]
我发现了一个可能的地方，如果背景类（0）也要参与计算的话，reduce_zero_label=True得改成False

**Comment by czczup** [comment]
> > @duanduanduanyuchen 看一看config
> 
> 您是叫他来看我的config吗？还是我去看他某个仓库的config？

是的，他会帮你看

**Comment by czczup** [comment]
还有一个地方，我看到你说图像是112x112的，你这里是直接pad到224x224吗，而不是resize到224x224

**Comment by czczup** [comment]
现在训练和测试的pipeline应该没有对齐，训练时是112pad到224，测试时是112resize224

**Comment by duanduanduanyuchen** [comment]
`assert (count_mat == 0).sum() == 0`
这段代码的含义是保证`count_mat`矩阵所有元素非0，`count_mat`矩阵是在测试的slide过程中的计数矩阵，目的在于对原图像进行切割、滑窗后进行测试的过程中，整张图片被滑窗完全覆盖。
根据你的config，在你的`model`变量中你设置的`crop_size`为`(224,224)`，在`test_pipeline`变量中设置的`img_scale`也为`(224,224)`，建议你检查在该段报错代码中的`img`的形状大小是否为`(224,224)`。

**Comment by 847001315** [comment]
> 现在训练和测试的pipeline应该没有对齐，训练时是112pad到224，测试时是112resize224，这可能会造成一些精度下降

非常感谢您替我解答~我去按照您的说法去更改一下，谢谢谢谢~~~

**Comment by 847001315** [comment]
> `assert (count_mat == 0).sum() == 0` 这段代码的含义是保证`count_mat`矩阵所有元素非0，`count_mat`矩阵是在测试的slide过程中的计数矩阵，目的在于对原图像进行切割、滑窗后进行测试的过程中，整张图片被滑窗完全覆盖。 根据你的config，在你的`model`变量中你设置的`crop_size`为`(224,224)`，在`test_pipeline`变量中设置的`img_scale`也为`(224,224)`，建议你检查在该段报错代码中的`img`的形状大小是否为`(224,224)`。

明白了~，也谢谢您替我解答~我再去补充一下相关知识，修改一下你们说的配置问题，再看看~，谢谢谢谢大家百忙之中抽空给我解答

**Comment by czczup** [comment]
> > `assert (count_mat == 0).sum() == 0` 这段代码的含义是保证`count_mat`矩阵所有元素非0，`count_mat`矩阵是在测试的slide过程中的计数矩阵，目的在于对原图像进行切割、滑窗后进行测试的过程中，整张图片被滑窗完全覆盖。 根据你的config，在你的`model`变量中你设置的`crop_size`为`(224,224)`，在`test_pipeline`变量中设置的`img_scale`也为`(224,224)`，建议你检查在该段报错代码中的`img`的形状大小是否为`(224,224)`。
> 
> 明白了~，也谢谢您替我解答~我再去补充一下相关知识，修改一下你们说的配置问题，再看看~，谢谢谢谢大家百忙之中抽空给我解答

我试了一下MMSeg自带的医学数据集CHASE_DB1，config如下，可以参考一下：
```
# Copyright (c) Shanghai AI Lab. All rights reserved.
_base_ = [
    '../_base_/models/upernet_beit.py',
    '../_base_/datasets/chase_db1.py',
    '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_40k.py'
]
img_scale = (960, 999)
crop_size = (128, 128)
# pretrained = 'https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_large_patch16_224_pt22k_ft22k.pth'
pretrained = 'pretrained/beit_large_patch16_224_pt22k_ft22k.pth'
model = dict(
    pretrained=pretrained,
    backbone=dict(
        type='BEiTAdapter',
        img_size=128,
        patch_size=16,
        embed_dim=1024,
        depth=24,
        num_heads=16,
        mlp_ratio=4,
        qkv_bias=True,
        use_abs_pos_emb=False,
        use_rel_pos_bias=True,
        init_values=1e-6,
        drop_path_rate=0.3,
        conv_inplane=64,
        n_points=4,
        deform_num_heads=16,
        cffn_ratio=0.25,
        deform_ratio=0.5,
        interaction_indexes=[[0, 5], [6, 11], [12, 17], [18, 23]],
    ),
    decode_head=dict(
        in_channels=[1024, 1024, 1024, 1024],
        num_classes=2,
        channels=1024,
    ),
    auxiliary_head=dict(
        in_channels=1024,
        num_classes=2
    ),
    test_cfg = dict(mode='slide', crop_size=crop_size, stride=(85, 85))
)
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='ResizeToMultiple', size_divisor=32),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
optimizer = dict(_delete_=True, type='AdamW', lr=2e-5, betas=(0.9, 0.999), weight_decay=0.05,
                 constructor='LayerDecayOptimizerConstructor',
                 paramwise_cfg=dict(num_layers=24, layer_decay_rate=0.90))
lr_config = dict(_delete_=True, policy='poly',
                 warmup='linear',
                 warmup_iters=1500,
                 warmup_ratio=1e-6,
                 power=1.0, min_lr=0.0, by_epoch=False)
data=dict(train=dict(pipeline=train_pipeline),
          val=dict(pipeline=test_pipeline),
          test=dict(pipeline=test_pipeline))
runner = dict(type='IterBasedRunner')
checkpoint_config = dict(by_epoch=False, interval=1000, max_keep_ckpts=1)
evaluation = dict(interval=4000, metric='mDice', save_best='mDice')
```

**Comment by 847001315** [comment]
> > > `assert (count_mat == 0).sum() == 0` 这段代码的含义是保证`count_mat`矩阵所有元素非0，`count_mat`矩阵是在测试的slide过程中的计数矩阵，目的在于对原图像进行切割、滑窗后进行测试的过程中，整张图片被滑窗完全覆盖。 根据你的config，在你的`model`变量中你设置的`crop_size`为`(224,224)`，在`test_pipeline`变量中设置的`img_scale`也为`(224,224)`，建议你检查在该段报错代码中的`img`的形状大小是否为`(224,224)`。
> > 
> > 
> > 明白了~，也谢谢您替我解答~我再去补充一下相关知识，修改一下你们说的配置问题，再看看~，谢谢谢谢大家百忙之中抽空给我解答
> 
> 我试了一下MMSeg自带的医学数据集CHASE_DB1，config如下，可以参考一下：
> 
> ```
> # Copyright (c) Shanghai AI Lab. All rights reserved.
> _base_ = [
>     '../_base_/models/upernet_beit.py',
>     '../_base_/datasets/chase_db1.py',
>     '../_base_/default_runtime.py',
>     '../_base_/schedules/schedule_40k.py'
> ]
> img_scale = (960, 999)
> crop_size = (128, 128)
> # pretrained = 'https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_large_patch16_224_pt22k_ft22k.pth'
> pretrained = 'pretrained/beit_large_patch16_224_pt22k_ft22k.pth'
> model = dict(
>     pretrained=pretrained,
>     backbone=dict(
>         type='BEiTAdapter',
>         img_size=128,
>         patch_size=16,
>         embed_dim=1024,
>         depth=24,
>         num_heads=16,
>         mlp_ratio=4,
>         qkv_bias=True,
>         use_abs_pos_emb=False,
>         use_rel_pos_bias=True,
>         init_values=1e-6,
>         drop_path_rate=0.3,
>         conv_inplane=64,
>         n_points=4,
>         deform_num_heads=16,
>         cffn_ratio=0.25,
>         deform_ratio=0.5,
>         interaction_indexes=[[0, 5], [6, 11], [12, 17], [18, 23]],
>     ),
>     decode_head=dict(
>         in_channels=[1024, 1024, 1024, 1024],
>         num_classes=2,
>         channels=1024,
>     ),
>     auxiliary_head=dict(
>         in_channels=1024,
>         num_classes=2
>     ),
>     test_cfg = dict(mode='slide', crop_size=crop_size, stride=(85, 85))
> )
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations'),
>     dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0)),
>     dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
>     dict(type='RandomFlip', prob=0.5),
>     dict(type='PhotoMetricDistortion'),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_semantic_seg'])
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=img_scale,
>         # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='ResizeToMultiple', size_divisor=32),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> optimizer = dict(_delete_=True, type='AdamW', lr=2e-5, betas=(0.9, 0.999), weight_decay=0.05,
>                  constructor='LayerDecayOptimizerConstructor',
>                  paramwise_cfg=dict(num_layers=24, layer_decay_rate=0.90))
> lr_config = dict(_delete_=True, policy='poly',
>                  warmup='linear',
>                  warmup_iters=1500,
>                  warmup_ratio=1e-6,
>                  power=1.0, min_lr=0.0, by_epoch=False)
> data=dict(train=dict(pipeline=train_pipeline),
>           val=dict(pipeline=test_pipeline),
>           test=dict(pipeline=test_pipeline))
> runner = dict(type='IterBasedRunner')
> checkpoint_config = dict(by_epoch=False, interval=1000, max_keep_ckpts=1)
> evaluation = dict(interval=4000, metric='mDice', save_best='mDice')
> ```

非常感谢您还抽空写了一下config！！我昨天吸收你们的建议后，去更改了一下，代码已经可以成功运行，并且iou并不会为0了。不过我遇到了问题，目前跑出来的结果，iou仅为60（deeplabv3跑该数据集可以iou=90），loss一直无法下降，目前仅仅调整学习率暂时无法解决，我会去再排查一下是否是我的config或者数据增强出现问题，也会参考您现在发的config，再一次感谢您回复我，十分感谢！！

**Comment by czczup** [comment]
昨天的config里好像没有加载预训练权重，不知道你后来有没有加上？

**Comment by 847001315** [comment]
> 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？

后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。

**Comment by czczup** [comment]
> > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> 
> 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。

可以载入的，finetune的分辨率可以和预训练不一致

**Comment by 847001315** [comment]
> > > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> > 
> > 
> > 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。
> 
> 可以载入的，finetune的分辨率可以和预训练不一致 这个模型比较大，医疗数据一般都比较少，如果不用预训练效果可能会比较差

好的！我后续去试验一下，刚刚开始接触mmseg框架，很多基础不清晰，非常打扰！！再一次感谢您！！想问一个问题，我的图片大小为112*112，test的mode选择whole和slide是否有影响？哪个模式更适合小图？whole吗？

**Comment by 847001315** [comment]
> > > > > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> > > > 
> > > > 
> > > > 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。
> > > 
> > > 
> > > 可以载入的，finetune的分辨率可以和预训练不一致 这个模型比较大，医疗数据一般都比较少，如果不用预训练效果可能会比较差
> > 
> > 
> > 好的！我后续去试验一下，刚刚开始接触mmseg框架，很多基础不清晰，非常打扰！！再一次感谢您！！想问一个问题，我的图片大小为112*112，test的mode选择whole和slide是否有影响？哪个模式更适合小图？whole吗？
> 
> 如果大小全部都是固定的112x112，用whole就好了

好的！了解了！！！vitadaper好像接受不了图尺寸为112X112的，我之前单独抽取把vitadapter抽取出来，放入之前自己的模型中，会出现有一个层的特征图为3x3，另外一个本来应该和它同尺度的特征图为4x4(说的很不清晰，后面我把它全部向上取整后，就可以跑了)。是否我可以认为，最低尺寸应该应该为128x128？

**Comment by czczup** [comment]
> > > > > > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> > > > > 
> > > > > 
> > > > > 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。
> > > > 
> > > > 
> > > > 可以载入的，finetune的分辨率可以和预训练不一致 这个模型比较大，医疗数据一般都比较少，如果不用预训练效果可能会比较差
> > > 
> > > 
> > > 好的！我后续去试验一下，刚刚开始接触mmseg框架，很多基础不清晰，非常打扰！！再一次感谢您！！想问一个问题，我的图片大小为112*112，test的mode选择whole和slide是否有影响？哪个模式更适合小图？whole吗？
> > 
> > 
> > 如果大小全部都是固定的112x112，用whole就好了
> 
> 好的！了解了！！！vitadaper好像接受不了图尺寸为112X112的，我之前单独抽取把vitadapter抽取出来，放入之前自己的模型中，会出现有一个层的特征图为3x3，另外一个本来应该和它同尺度的特征图为4x4(说的很不清晰，后面我把它全部向上取整后，就可以跑了)。是否我可以认为，最低尺寸应该应该为128x128？

确实。要求输入图像的分辨率能被32整除(因为最小的特征图是stride 32的)，倒不一定是128x128

**Comment by 847001315** [comment]
> > > > > > > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> > > > > > 
> > > > > > 
> > > > > > 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。
> > > > > 
> > > > > 
> > > > > 可以载入的，finetune的分辨率可以和预训练不一致 这个模型比较大，医疗数据一般都比较少，如果不用预训练效果可能会比较差
> > > > 
> > > > 
> > > > 好的！我后续去试验一下，刚刚开始接触mmseg框架，很多基础不清晰，非常打扰！！再一次感谢您！！想问一个问题，我的图片大小为112*112，test的mode选择whole和slide是否有影响？哪个模式更适合小图？whole吗？
> > > 
> > > 
> > > 如果大小全部都是固定的112x112，用whole就好了
> > 
> > 
> > 好的！了解了！！！vitadaper好像接受不了图尺寸为112X112的，我之前单独抽取把vitadapter抽取出来，放入之前自己的模型中，会出现有一个层的特征图为3x3，另外一个本来应该和它同尺度的特征图为4x4(说的很不清晰，后面我把它全部向上取整后，就可以跑了)。是否我可以认为，最低尺寸应该应该为128x128？
> 
> 确实。要求输入图像的分辨率能被32整除(因为最小的特征图是stride 32的)，倒不一定是128x128

好的！！！非常感谢╰(*´︶`*)╯！！如果我对mmseg和vit-adapter更熟悉了之后，是否可以写一个博客用来介绍如何在本项目中自定义数据集？

**Comment by czczup** [comment]
> > > > > > > > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> > > > > > > 
> > > > > > > 
> > > > > > > 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。
> > > > > > 
> > > > > > 
> > > > > > 可以载入的，finetune的分辨率可以和预训练不一致 这个模型比较大，医疗数据一般都比较少，如果不用预训练效果可能会比较差
> > > > > 
> > > > > 
> > > > > 好的！我后续去试验一下，刚刚开始接触mmseg框架，很多基础不清晰，非常打扰！！再一次感谢您！！想问一个问题，我的图片大小为112*112，test的mode选择whole和slide是否有影响？哪个模式更适合小图？whole吗？
> > > > 
> > > > 
> > > > 如果大小全部都是固定的112x112，用whole就好了
> > > 
> > > 
> > > 好的！了解了！！！vitadaper好像接受不了图尺寸为112X112的，我之前单独抽取把vitadapter抽取出来，放入之前自己的模型中，会出现有一个层的特征图为3x3，另外一个本来应该和它同尺度的特征图为4x4(说的很不清晰，后面我把它全部向上取整后，就可以跑了)。是否我可以认为，最低尺寸应该应该为128x128？
> > 
> > 
> > 确实。要求输入图像的分辨率能被32整除(因为最小的特征图是stride 32的)，倒不一定是128x128
> 
> 好的！！！非常感谢╰(_´︶`_)╯！！如果我对mmseg和vit-adapter更熟悉了之后，是否可以写一个博客用来介绍如何在本项目中自定义数据集？

当然可以😊

**Comment by 847001315** [comment]
您好~ 我这两天去把您之前说的发的config进行修改一些路径，已经可以跑了，并且得到了比deeplabv3_resnet50更好的效果。但是我在跑另外一个3类别数据集【如果加上背景是4类，但我并不打算计算背景】的时候，验证集的对于这三个类还能达到姣好的效果，但测试集得出来的结果仅有0和2两个像素值，没有1像素值，也没有其它像素值，目前我打算去将背景也加为一类，但是我有点困惑，如果说背景不加入其中的话，那确实分割出来只会有三个可能的像素值【但城市景观好像就没有背景类？】。所以想问：
1. 如果我没将背景（像素值255）也算作一类，是否会影响分类结果？
2. 测试集仅得出了0和2的像素值，并没有1的像素值，这可能存在什么原因？
以下是验证集得到的结果：
![O5D%ZFPS$R98PJ8LH08{7K0](https://user-images.githubusercontent.com/49674990/174856180-66a59f24-dd16-450d-a749-1562c96a4f24.png)

我接下来会将背景类加入~ 
非常感谢您！！

**Comment by 847001315** [comment]
> 

好的，谢谢您！
我之前设置的reduce_zero_label=false，然后0 1 2 为具体的三个目标类，我手动将mask的背景设为255。请问mmseg默认255是不计算的吗？
对于第三点，我马上去尝试

**Comment by 847001315** [comment]
> > 您好~ 我这两天去把您之前说的发的config进行修改一些路径，已经可以跑了，并且得到了比deeplabv3_resnet50更好的效果。但是我在跑另外一个3类别数据集【如果加上背景是4类，但我并不打算计算背景】的时候，验证集的对于这三个类还能达到姣好的效果，但测试集得出来的结果仅有0和2两个像素值，没有1像素值，也没有其它像素值，目前我打算去将背景也加为一类，但是我有点困惑，如果说背景不加入其中的话，那确实分割出来只会有三个可能的像素值【但城市景观好像就没有背景类？】。所以想问：
> > 
> > 1. 如果我没将背景（像素值255）也算作一类，是否会影响分类结果？
> > 2. 测试集仅得出了0和2的像素值，并没有1的像素值，这可能存在什么原因？
> >    以下是验证集得到的结果：
> >    ![O5D%ZFPS$R98PJ8LH08{7K0](https://user-images.githubusercontent.com/49674990/174856180-66a59f24-dd16-450d-a749-1562c96a4f24.png)
> > 
> > 我接下来会将背景类加入~ 非常感谢您！！
> 
> 1. 背景不参与是可以的，不过通常像素值0是背景，而255是要忽略的像素
> 2. 请问你的reduce_zero_label是设的什么
> 3. 我有一个办法应该可以解决，就是重新映射一下标签，背景为0，其他的为1、2、3，reduce_zero_label=True

好的，谢谢您！
我之前设置的reduce_zero_label=false，然后0 1 2 为具体的三个目标类，我手动将mask的背景设为255。请问mmseg默认255是不计算的吗？
对于第三点，我马上去尝试

**Comment by JavaZeroo** [comment]
> > > > > > > > 昨天的config里好像没有加载预训练权重`pretrained=None`，不知道你后来有没有加上？
> > > > > > > 
> > > > > > > 
> > > > > > > 后面依旧没有加上，有一个疑惑，例如您刚刚给我发的config中的model的backbone的image_size为128，但预训练权重是224的，是否可以载入？我一开始感觉我的图像尺寸和model的backbone尺寸不同就没有加，后续可以去加一下。
> > > > > > 
> > > > > > 
> > > > > > 可以载入的，finetune的分辨率可以和预训练不一致 这个模型比较大，医疗数据一般都比较少，如果不用预训练效果可能会比较差
> > > > > 
> > > > > 
> > > > > 好的！我后续去试验一下，刚刚开始接触mmseg框架，很多基础不清晰，非常打扰！！再一次感谢您！！想问一个问题，我的图片大小为112*112，test的mode选择whole和slide是否有影响？哪个模式更适合小图？whole吗？
> > > > 
> > > > 
> > > > 如果大小全部都是固定的112x112，用whole就好了
> > > 
> > > 
> > > 好的！了解了！！！vitadaper好像接受不了图尺寸为112X112的，我之前单独抽取把vitadapter抽取出来，放入之前自己的模型中，会出现有一个层的特征图为3x3，另外一个本来应该和它同尺度的特征图为4x4(说的很不清晰，后面我把它全部向上取整后，就可以跑了)。是否我可以认为，最低尺寸应该应该为128x128？
> > 
> > 
> > 确实。要求输入图像的分辨率能被32整除(因为最小的特征图是stride 32的)，倒不一定是128x128
> 
> 好的！！！非常感谢╰(_´︶`_)╯！！如果我对mmseg和vit-adapter更熟悉了之后，是否可以写一个博客用来介绍如何在本项目中自定义数据集？

哥们，博客写好了吗😁
