### ISSUE TITLE
ModuleNotFoundError: No module named 'ops.modules'

### ISSUE THREAD

**Issue by leetesua** [czczup/ViT-Adapter#12]
![fe70a4dece84fc20d600436d54dc14e](https://user-images.githubusercontent.com/25045281/174788617-49a58787-1f91-49dc-9adf-272d86846614.png)

**Comment by leetesua** [comment]
I installed "ops" package via pip install ops, but still got this bug. Where need to be changed to fix this?

**Comment by czczup** [comment]
Hi, you should do like this:
```
ln -s ../detection/ops ./
cd ops & sh make.sh # compile deformable attention
```

**Comment by leetesua** [comment]
thanks for your quick reply！
