### ISSUE TITLE
Mask2former Pretrained on Pascal VOC

### ISSUE THREAD

**Issue by yaldashbz** [czczup/ViT-Adapter#121]
Hi, 
Is this model [config](https://github.com/czczup/ViT-Adapter/blob/main/segmentation/configs/pascal_context/mask2former_beit_adapter_base_480_40k_pascal_context_59_ms.py) is a pretrained mask2former model on pascal?

**Comment by czczup** [comment]
Yes, you can download the pretrained weights from 
https://github.com/czczup/ViT-Adapter/releases/download/v0.2.8/mask2former_beit_adapter_base_480_40k_pascal_context_59.pth.tar
