### ISSUE TITLE
Dinov2 mmcv compatability

### ISSUE THREAD

**Issue by studentWUR** [czczup/ViT-Adapter#124]
As far as I know dinov2 only works with pytorch2.0. 
By using pytorch2.0 I am able to load the pretrained models of Dino. 
However, mmcv-full 1.xx is not compatible with pytorch2.0. 
Does anyone know how to install the dependencies for dinov2 compatability.

**Comment by czczup** [comment]
You can use torch 1.x to load the pretrained weights of dinov2.

**Comment by studentWUR** [comment]
Thank you for the quick answer, I tried, but I got the error message that torch was missing "_rebuild_from_type_v2"

**Comment by Harry-zzh** [comment]
> Thank you for the quick answer, I tried, but I got the error message that torch was missing "_rebuild_from_type_v2"

I also met the same issue. Installing PyTorch version >= 1.10.0 can solve this problem.

**Comment by czczup** [comment]
> > Thank you for the quick answer, I tried, but I got the error message that torch was missing "_rebuild_from_type_v2"
> 
> I also met the same issue. Installing PyTorch version >= 1.10.0 can solve this problem.

thanks for your feedback
