### ISSUE TITLE
How can adapter be used in other sizes of vit?

### ISSUE THREAD

**Issue by zhl98** [czczup/ViT-Adapter#127]
Hello

Thank you very much for your work. I would like to know how to add adapter to other sizes of vits, such as vit g?

**Comment by zhl98** [comment]
Thank you very much for your reply. 
However, I still encountered a problem when using my patch_ The size is 14.

I would like to inquire about deform_inputs1, deform_inputs2 don't think the  variables are learnable parameters in the code, or are they calculated from the input. Do they have no impact as long as the dimensions match? What dimensions should they be?

**Comment by czczup** [comment]
You should resize the patch embedding from 14 to 16. 
Like these models: https://github.com/czczup/ViT-Adapter/tree/main/detection/configs/mask_rcnn/dinov2

**Comment by ds2268** [comment]
@czczup: Shouldn't we also transform `pos_embed` weights to 16 x 16? (currently converting just patch_embed)
