### ISSUE TITLE
here is an problem with MS deform

### ISSUE THREAD

**Issue by he13689** [czczup/ViT-Adapter#13]
when I run the following sentence:
output = MSDA.ms_deform_attn_forward(value, value_spatial_shapes, value_level_start_index, sampling_locations, attention_weights, ctx.im2col_step)

The error occurs:
type object 'MultiScaleDeformableAttention' has no attribute 'ms_deform_attn_forward'

pls help, Thanks

**Comment by czczup** [comment]
> when I run the following sentence: output = MSDA.ms_deform_attn_forward(value, value_spatial_shapes, value_level_start_index, sampling_locations, attention_weights, ctx.im2col_step)
> 
> The error occurs: type object 'MultiScaleDeformableAttention' has no attribute 'ms_deform_attn_forward'
> 
> pls help, Thanks

Hello, which task are you running on, detection or segmentation?
I recommend checking if deformable attention is compiled correctly.
The commends to compile deformable attention are:
For detection:
```
cd detection/
cd ops & sh make.sh
```

For segmentation:
```
cd segmentation/
ln -s ../detection/ops ./
cd ops & sh make.sh
```

**Comment by he13689** [comment]
thank u, the deformable attention is not compiled yet, and I run the setup.py under the ./detection/ops folder
I can not run the make.sh cause I use the win10 system

I really appreciate it, @czczup
