### ISSUE TITLE
What is the principle of feature map visualization?

### ISSUE THREAD

**Issue by facias914** [czczup/ViT-Adapter#132]
Hi ！ The research in this paper is an excellent work

By the way, I would like to ask what is the principle of feature map visualization in the paper. Is it simply a matter of regularizing each channel of the feature map and then adding up all the channels to take the mean?

Does the feature map visualization in the detection task have the same effect as the feature map visualization in the segmentation task?

**Comment by czczup** [comment]
Hi, please see the issue #76.
