### ISSUE TITLE
How to freeze ViT backbone during training?

### ISSUE THREAD

**Issue by zzzqzhou** [czczup/ViT-Adapter#136]
I want to freeze ViT backbone during training on some downstream tasks. How can I change the config or the code?

**Comment by czczup** [comment]
You can write some code on the train.py to freeze ViT backbone, like this code:

<img width="594" alt="image" src="https://github.com/czczup/ViT-Adapter/assets/23737120/c6c50d37-75bf-4822-84ea-ae7b50bb297d">

**Comment by zzzqzhou** [comment]
Thanks a lot!
