### ISSUE TITLE
The memory cost.

### ISSUE THREAD

**Issue by kunpingyang** [czczup/ViT-Adapter#14]
你好，cityscapes_val_84.9的那个模型能在32G的显卡上跑吗，我用A6000都跑不了，一张卡一张图都爆。是文章里面是冻结了参数嘛，还是咋弄的。

**Comment by kunpingyang** [comment]
我用A6000训练也只能一张卡一张图（896size的），其他地方都没动过。

**Comment by czczup** [comment]
> 你好，cityscapes_val_84.9的那个模型能在32G的显卡上跑吗，我用A6000都跑不了，一张卡一张图都爆。是文章里面是冻结了参数嘛，还是咋弄的。

你好，这个模型因为输入分辨率高(896)以及参数量大(~500M)，需要的显存会比较多。我刚刚给分割代码更新了with_cp功能，在开启with_cp之后，一张卡一张图大约需要21G显存[link](https://github.com/czczup/ViT-Adapter/blob/main/segmentation/configs/cityscapes/mask2former_beit_adapter_large_896_80k_cityscapes_ss.py)。你可以更新一下最新的代码再尝试一下。

**Comment by kunpingyang** [comment]
> 

喔喔，感谢

**Comment by kunpingyang** [comment]
> > 你好，cityscapes_val_84.9的那个模型能在32G的显卡上跑吗，我用A6000都跑不了，一张卡一张图都爆。是文章里面是冻结了参数嘛，还是咋弄的。
> 
> 你好，这个模型因为输入分辨率高(896)以及参数量大(~500M)，需要的显存会比较多。我刚刚给分割代码更新了with_cp功能，在开启with_cp之后，一张卡一张图大约需要21G显存[link](https://github.com/czczup/ViT-Adapter/blob/main/segmentation/configs/cityscapes/mask2former_beit_adapter_large_896_80k_cityscapes_ss.py)。你可以更新一下最新的代码再尝试一下。

喔喔，感谢
