### ISSUE TITLE
LayerScale and pre-trained models

### ISSUE THREAD

**Issue by ds2268** [czczup/ViT-Adapter#157]
> Hi, your notebook is very good. All the steps are correct. This output is just a warning, not an error. This warning is due to the use of LayerScale in our model, which was not included in the original DeiT pre-trained weights. The output of `image_demo.py` is saved as a file in `demo/`. You can check if this file is generated.

LayerScale is usually not used in MAE pre-trained VITs (e.g., for classification, ImageNet). Can you still use such pre-trained weights (ignoring the warning) or are LayerScale learned parameters influencing other learned features? Basically, can you use pre-trained weights from ViTs pre-pre-trained models with LayerScale = False and then use them to fine-tune on the ViT-Adapter which has LayerScale=True

The issue is partially related to #34.

**Comment by ds2268** [comment]
Looks like you are using DeiT weights for the pre-trained model that was NOT trained with LayerScale ([config file](https://github.com/czczup/ViT-Adapter/blob/main/detection/configs/mask_rcnn/mask_rcnn_deit_adapter_base_fpn_3x_coco.py)). You then fine-tune ViT using the ViT-Adapter which initializes ViT with LayerScale layers. LayerScale layers are by default initialized to close to 0 (original LayerScale paper). The pre-trained features are then scaled with LayerScale, which effectively pushes them (close) to 0 if the LayerScale weights are not optimized to 1 quickly (identity).

I think that pre-trained should be trained with LayerScale in order to be transferable to ViT-Adapter, which has LayerScale=True by default, which is not the case in TIMM or Torch.

@czczup can you elaborate on that?

**Comment by czczup** [comment]
I'm really sorry for the late reply. 

Regarding your question, my answer is: You can use the pre-trained weights from the ViT pre-trained model (LayerScale = False) and then fine-tune them on a ViT adapter with LayerScale=True. You just need to set the initial value of LayerScale to 1. 

Before starting the training of the model (LayerScale=True, init_value=1.0), the inference results will be equivalent to those with LayerScale = False.

**Comment by czczup** [comment]
I just checked the code, for instance, the ViT code in the detection package, like [this](https://github.com/czczup/ViT-Adapter/blob/main/detection/mmdet_custom/models/backbones/base/vit.py#L315). When using layer scale, I hard-coded the initial value to be 1.0. Thus the warnings about the failure to load these weights can be ignored.

<img width="766" alt="image" src="https://github.com/czczup/ViT-Adapter/assets/23737120/5526a9b1-11a3-4cb8-b5ff-534531855915">

**Comment by czczup** [comment]
It's important to note that in the ViTAdapter class, there is an 'init_values' parameter with a default value of 0. This is used to control the injector module of the adapter, not the layer scale of the ViT itself.

<img width="788" alt="image" src="https://github.com/czczup/ViT-Adapter/assets/23737120/3d384436-12a0-4345-8caa-b6aec98f47ce">
<img width="683" alt="image" src="https://github.com/czczup/ViT-Adapter/assets/23737120/aba59ab1-4038-433d-970f-4e24ce17b59e">

**Comment by ds2268** [comment]
Thanks a lot @czczup  I think that this clarifies everything!
