### ISSUE TITLE
Missing pretrained weights

### ISSUE THREAD

**Issue by manu15sd** [czczup/ViT-Adapter#162]
Hi, I'm trying to train a model for the Cityscapes dataset, but when loading the pretrained weights, it raises an error because I don't have permissions to download it. This is the URL that is not working: "https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_large_patch16_224_pt22k_ft22k.pth"

**Comment by czczup** [comment]
Hi, you can download this pretrained weight from here: https://github.com/microsoft/unilm/tree/master/beit
