### ISSUE TITLE
关于drop path rate的问题

### ISSUE THREAD

**Issue by Wenlve-Zhou** [czczup/ViT-Adapter#167]
您好！感谢你们的工作，我留意到你们不同规模的adapter模型使用了不同的drop path rate，而且每一层的adapter的drop path rate似乎都是一致的，这与一般的逐层递增规则似乎不同。drop path rate在这里的设置有什么规律吗？对模型的精度是否会有很大的影响？

**Comment by czczup** [comment]
您好，ViT内使用的是递增的drop path rate，而Adapter里使用的是固定的drop path rate，这是因为当时代码实现的时候没有注意到逐层递增这个细节，不是故意这么设置的。不过在这用哪种drop path rate对结果都不会有太大影响。
