### ISSUE TITLE
Question about masking the input when using MAE weights with ViT-Adapter.

### ISSUE THREAD

**Issue by praeclarumjj3** [czczup/ViT-Adapter#17]
Hi, thanks for your great work. I was looking at your config file for [mask_rcnn_mae_adapter_base_lsj_fpn_25ep_coco.py](https://github.com/czczup/ViT-Adapter/blob/b9c2a7060c1984bb2eaac6d193a2efd2aabb481b/detection/configs/upgraded_mask_rcnn/mask_rcnn_mae_adapter_base_lsj_fpn_25ep_coco.py) which uses the MAE pretrained weights with the ViTAdapter backbone. I could not find any specification for the masking ratio for the input. 

When looking at the [`vit.py`](https://github.com/czczup/ViT-Adapter/blob/b9c2a7060c1984bb2eaac6d193a2efd2aabb481b/detection/mmdet_custom/models/backbones/base/vit.py) and [`vit_adpater.py`](https://github.com/czczup/ViT-Adapter/blob/b9c2a7060c1984bb2eaac6d193a2efd2aabb481b/detection/mmdet_custom/models/backbones/vit_adapter.py) files, I could not find any method that performs [random masking](https://github.com/hustvl/MIMDet/blob/67fb43ee80765aa214d57ade7279632b4d80b8e5/models/mimdet.py#L186) on the input which is the usual norm with the MAE based works. Am I missing something here? How do you ensure the masking, or do you input without any masking? Thanks

**Comment by duanduanduanyuchen** [comment]
Hi, thank you for your attention! We actually load MAE pretrained weights to the ViT backbone, not use the mask method in training, so there's no need to set a mask ratio.

**Comment by praeclarumjj3** [comment]
Hi, thanks for your quick reply! Did you find masking harmful during training, or do you have any ablations on that? My guess is that the masking ratio during training on downstream tasks should affect the performance.

**Comment by duanduanduanyuchen** [comment]
> Hi, thanks for your quick reply! Did you find masking harmful during training, or do you have any ablations on that? My guess is that the masking ratio during training on downstream tasks should affect the performance.

Thank you for your advice! We haven't try the masking task during training yet. 
The only purpose of loading the pretrained weights to ViT is to give the model a strong prior of vision tasks. Our main idea is the design of the adapter and the paradigm in vision of loading existing pretrained weights and adapt the model to downstream dense prediction tasks. So we didn't pay attention to the training methods of pretrained weights. These methods may have a positive effect in dense prediction tasks, but are not quite related to the design of our adapter. We may try that in our later work.

**Comment by praeclarumjj3** [comment]
> > Hi, thanks for your quick reply! Did you find masking harmful during training, or do you have any ablations on that? My guess is that the masking ratio during training on downstream tasks should affect the performance.
> 
> Thank you for your advice! We haven't try the masking task during training yet. The only purpose of loading the pretrained weights to ViT is to give the model a strong initialization of vision tasks. Our main idea is the design of the adapter and the paradigm in vision of loading existing pretrained weights and adapt the model to downstream dense prediction tasks. So we didn't pay attention to the training methods of pretrained weights. These methods may have a positive effect in dense prediction tasks, but are not quite related to the design of our adapter. We may try that in our later work.

Thanks for the clarification! Looking forward to your later work.
