### ISSUE TITLE
Broken Download Links

### ISSUE THREAD

**Issue by HugeBob** [czczup/ViT-Adapter#2]
Hello, when attempting to download SOTA pre-trained models COCO-Stuff-164k on ADE20k or Mapillary on Cityscapes, it redirects to the GitHub broken link page.

**Comment by czczup** [comment]
> Hello, when attempting to download SOTA pre-trained models COCO-Stuff-164k on ADE20k or Mapillary on Cityscapes, it redirects to the GitHub broken link page.

Hi, these files have not been uploaded, so there is no download link yet.
I'm putting together these codes and models, I'll upload them soon. This may take a few days.

**Comment by czczup** [comment]
Code and models for segmentation have been released.

**Comment by HugeBob** [comment]
Thank you!
