### ISSUE TITLE
请问base.py获取的batch_data对应的mmseg版本是什么呢？

### ISSUE THREAD

**Issue by xu19971109** [czczup/ViT-Adapter#20]
我用的之前可以成功跑通的mmseg包，打印出来的batch_data的keys()为：
![微信图片_20220707193638](https://user-images.githubusercontent.com/50237122/177765325-7242eb6e-eb75-43ae-9fb4-80e7e153f726.png)
现在训练博主的代码的时候，把mmseg和mmcv都移动到segmentation下，并make.sh了环境。发现batch_data超过except 2之后，我将batch_data去掉了多余的key，目前报如下错误：
![微信图片_20220707193955](https://user-images.githubusercontent.com/50237122/177765502-02f09bab-8d81-4b25-ab3f-5ad424f0842d.png)
请问我应该更换mmseg的版本吗，我是用的是0.24版本

**Comment by czczup** [comment]
我用的是0.20.2的mmsegmentation，直接`pip install mmsegmentation==0.20.2`即可，不确定更高的版本是否有兼容问题

**Comment by xu19971109** [comment]
好的，辛苦老师了~



---- 回复的原邮件 ----
| 发件人 | Zhe ***@***.***> |
| 日期 | 2022年07月07日 22:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [czczup/ViT-Adapter] 请问base.py获取的batch_data对应的mmseg版本是什么呢？ (Issue #20) |

我用的是0.20.2的mmsegmentation，直接pip install mmsegmentation==0.20.2即可，不确定更高的版本是否有兼容问题
