### ISSUE TITLE
关于更新pytorch1.12后遇到的问题

### ISSUE THREAD

**Issue by 834799106** [czczup/ViT-Adapter#21]
您好，由于另个项目需要，我把pytorch升级为最新版本，在这之后我再运行vit-adapter部分代码会出现一下问题：
File "/data0/ops/modules/ms_deform_attn.py", line 127, in forward
    output = MSDeformAttnFunction.apply(value, input_spatial_shapes, input_level_start_index,
  File "/home/.conda/envs/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/data0/ops/functions/ms_deform_attn_func.py", line 25, in forward
    output = MSDA.ms_deform_attn_forward(value, value_spatial_shapes,
RuntimeError: Unrecognized tensor type ID: PythonTLSSnapshot
Exception raised from dispatchKeyToBackend at /home/.conda/envs/lib/python3.9/site-packages/torch/include/c10/core/Backend.h:110 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7fde793da1ee in /home/.conda/envs/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7fde793b55e8 in /home/.conda/envs/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x3cd14 (0x7fe29fbacd14 in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so)
frame #3: ms_deform_attn_forward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, int) + 0x82 (0x7fe29fbad0b2 in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x4950a (0x7fe29fbb950a in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x46676 (0x7fe29fbb6676 in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so)

当然，这只是一个使用后的反馈，毕竟安装独立环境就能解决这个问题

**Comment by czczup** [comment]
> 您好，由于另个项目需要，我把pytorch升级为最新版本，在这之后我再运行vit-adapter部分代码会出现一下问题： File "/data0/ops/modules/ms_deform_attn.py", line 127, in forward output = MSDeformAttnFunction.apply(value, input_spatial_shapes, input_level_start_index, File "/home/.conda/envs/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd return fwd(*_cast(args, cast_inputs), ___cast(kwargs, cast_inputs)) File "/data0/ops/functions/ms_deform_attn_func.py", line 25, in forward output = MSDA.ms_deform_attn_forward(value, value_spatial_shapes, RuntimeError: Unrecognized tensor type ID: PythonTLSSnapshot Exception raised from dispatchKeyToBackend at /home/.conda/envs/lib/python3.9/site-packages/torch/include/c10/core/Backend.h:110 (most recent call first): frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7fde793da1ee in /home/.conda/envs/lib/python3.9/site-packages/torch/lib/libc10.so) frame #1: c10::detail::torchCheckFail(char const_, char const_, unsigned int, std::string const&) + 0x5c (0x7fde793b55e8 in /home/.conda/envs/lib/python3.9/site-packages/torch/lib/libc10.so) frame #2: + 0x3cd14 (0x7fe29fbacd14 in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so) frame #3: ms_deform_attn_forward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, int) + 0x82 (0x7fe29fbad0b2 in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so) frame #4: + 0x4950a (0x7fe29fbb950a in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so) frame #5: + 0x46676 (0x7fe29fbb6676 in /home/.conda/envs/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so)
> 
> 当然，这只是一个使用后的反馈，毕竟安装独立环境就能解决这个问题

感谢反馈
