### ISSUE TITLE
How can I follow this great work if I do NOT have 16 Nvidia A100 (80GB)? 

### ISSUE THREAD

**Issue by rayleizhu** [czczup/ViT-Adapter#22]
HI, thanks for your insightful work. I notice that, you use 8 or even 16 80GB A100 graphics cards to conduct the experiments (e.g. [ViT-L-Mask2Former@ADE20K](https://github.com/czczup/ViT-Adapter/releases/download/v0.2.0/20220430_154104.log) and [ViT-L-Mask2Former@CityScape](https://github.com/czczup/ViT-Adapter/releases/download/v0.2.3/log.txt) ). However, I do not have such powerful computing resources, the most powerful graphics card I can access is 2080Ti, can you kindly give some suggestions? 

Many thanks!

**Comment by duanduanduanyuchen** [comment]
> HI, thanks for your insightful work. I notice that, you use 8 or even 16 80GB A100 graphics cards to conduct the experiments (e.g. [ViT-L-Mask2Former@ADE20K](https://github.com/czczup/ViT-Adapter/releases/download/v0.2.0/20220430_154104.log) and [ViT-L-Mask2Former@CityScape](https://github.com/czczup/ViT-Adapter/releases/download/v0.2.3/log.txt) ). However, I do not have such powerful computing resources, the most powerful graphics card I can access is 2080Ti, can you kindly give some suggestions?
> 
> Many thanks!

Thanks for your attention on our work! I think you can try the ViT-L-Upernet model on 2080Ti.
