### ISSUE TITLE
Can I do instance segmentation with ground-truth bounding box?

### ISSUE THREAD

**Issue by chenzhutian** [czczup/ViT-Adapter#25]
Thanks for sharing the great repo!
I have a few GT bounding box of several overlapped objects. I am wondering if it is possible to use these GT bbox to do insance segmentation? If so, how? Thanks!

**Comment by czczup** [comment]
Hello, you can check the [documentation](https://mmdetection.readthedocs.io/en/stable/) of mmdet to see if it has this function.  Maybe you need to modify the inference code for mmdet.
