### ISSUE TITLE
请问cityscapes语义分割中mapillary预训练模型对应的config文件是哪一个？

### ISSUE THREAD

**Issue by githubcvcv** [czczup/ViT-Adapter#26]
![1](https://user-images.githubusercontent.com/109346193/179647173-d35f1d02-a44c-4d6a-b60f-1dd0581ca649.png)
请问如果想用图中的mapillary预训练模型（mask2former_beit_adapter_large_896_80k_mapillary.zip）做语义分割的话？config文件该用哪一个呢？是“mask2former_beit_adapter_large_896_80k_mapillary_ss.py”吗？

**Comment by czczup** [comment]
> ![1](https://user-images.githubusercontent.com/109346193/179647173-d35f1d02-a44c-4d6a-b60f-1dd0581ca649.png) 请问如果想用图中的mapillary预训练模型（mask2former_beit_adapter_large_896_80k_mapillary.zip）做语义分割的话？config文件该用哪一个呢？是“mask2former_beit_adapter_large_896_80k_mapillary_ss.py”吗？

是的，是这个config

**Comment by githubcvcv** [comment]
> 

好的，谢谢！
