### ISSUE TITLE
ade20k 640x640

### ISSUE THREAD

**Issue by ydhongHIT** [czczup/ViT-Adapter#31]
The mmseg official code uses the image scale of (2560, 640) while this repo uses (2048, 640).

**Comment by czczup** [comment]
> The mmseg official code uses the image scale of (2560, 640) while this repo uses (2048, 640).

Hi, in the ADE20K dataset, the long side of images does not exceed 2048 when the short side is 640, so both these two settings are the same. You can use (2560, 640) like mmseg.
