### ISSUE TITLE
 No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by Jinshan99** [czczup/ViT-Adapter#37]
Hello, when I import mmseg_custom, it gave this error... Could you help me to fix it, Thank you!!!~~~

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_208157/151112096.py in <module>
      1 get_ipython().run_line_magic('cd', '/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation')
----> 2 import mmseg_custom

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/mmseg_custom/__init__.py in <module>
      1 from .core import *  # noqa: F401,F403
      2 from .datasets import *  # noqa: F401,F403
----> 3 from .models import *  # noqa: F401,F403

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/mmseg_custom/models/__init__.py in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .backbones import *  # noqa: F401,F403
      3 from .builder import (MASK_ASSIGNERS, MATCH_COST, TRANSFORMER, build_assigner,
      4                       build_match_cost)
      5 from .decode_heads import *  # noqa: F401,F403

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/mmseg_custom/models/backbones/__init__.py in <module>
      1 # Copyright (c) Shanghai AI Lab. All rights reserved.
----> 2 from .beit_adapter import BEiTAdapter
      3 from .beit_baseline import BEiTBaseline
      4 from .vit_adapter import ViTAdapter
      5 from .vit_baseline import ViTBaseline

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/mmseg_custom/models/backbones/beit_adapter.py in <module>
      8 import torch.nn.functional as F
      9 from mmseg.models.builder import BACKBONES
---> 10 from ops.modules import MSDeformAttn
     11 from timm.models.layers import DropPath, trunc_normal_
     12 from torch.nn.init import normal_

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/ops/modules/__init__.py in <module>
      7 # ------------------------------------------------------------------------------------------------
      8 
----> 9 from .ms_deform_attn import MSDeformAttn
     10 
     11 __all__ = ['MSDeformAttn']

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/ops/modules/ms_deform_attn.py in <module>
     17 from torch.nn.init import constant_, xavier_uniform_
     18 
---> 19 from ..functions import MSDeformAttnFunction
     20 
     21 

<module>
      7 # ------------------------------------------------------------------------------------------------
      8 
----> 9 from .ms_deform_attn_func import MSDeformAttnFunction
     10 
     11 __all__ = ['MSDeformAttnFunction']

/media/preethamam/Utilities-SSD-1/Xtreme_Programming/Jinshan/ViT-Adapter/segmentation/ops/functions/ms_deform_attn_func.py in <module>
      9 from __future__ import absolute_import, division, print_function
     10 
---> 11 import MultiScaleDeformableAttention as MSDA
     12 import torch
     13 import torch.nn.functional as F

ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

**Comment by Akinpzx** [comment]
You must run (sh make.sh) in the ops directory

**Comment by czczup** [comment]
Hi, please refer to issue #13 to compile the deform attention ops.
