### ISSUE TITLE
Test script for single image or webcam

### ISSUE THREAD

**Issue by Zzzzzczc** [czczup/ViT-Adapter#4]
Hi. Thank you for sharing your work.
Is there any chance to release a script for testing a single image, or maybe allowing for webcam usage?

**Comment by czczup** [comment]
> Hi. Thank you for sharing your work. Is there any chance to release a script for testing a single image, or maybe allowing for webcam usage?

Hi, I add a script for single image inference of segmentation. You can use it like this:
```
cd segmentation
CUDA_VISIBLE_DEVICES=0 python image_demo.py \
  configs/ade20k/mask2former_beit_adapter_large_896_80k_ade20k_ss.py  \
  released/mask2former_beit_adapter_large_896_80k_ade20k.pth.tar  \
  data/ade/ADEChallengeData2016/images/validation/ADE_val_00000591.jpg \
  --palette ade20k 
```
The result will be saved at `demo/ADE_val_00000591.jpg`.
![image](https://user-images.githubusercontent.com/23737120/172036201-ae8da89b-6374-452c-b944-1175195af5e0.png)

**Comment by Zzzzzczc** [comment]
Thank you very much!

**Comment by wesley960** [comment]
I've imported everything listed under Usage on the Segmentation page
![Screen Shot 2022-06-05 at 3 54 38 PM](https://user-images.githubusercontent.com/106930430/172068527-2bb0629a-cbf1-4453-ba5e-0baefca5325e.png)

**Comment by czczup** [comment]
> I've imported everything listed under Usage on the Segmentation page, what am I missing? https://github.com/czczup/ViT-Adapter/tree/main/segmentation
> 
> ![Screen Shot 2022-06-05 at 3 54 38 PM](https://user-images.githubusercontent.com/106930430/172068527-2bb0629a-cbf1-4453-ba5e-0baefca5325e.png)

Hi, did you compile deformable attention. Like this:
```
cd segmentation/
ln -s ../detection/ops ./
cd ops
sh make.sh
```

**Comment by wesley960** [comment]
Says CUDA not available. I know PyTorch recently released support for training on M1 Macs, but do you think the problem could be M1 related?

![Screen Shot 2022-06-06 at 1 07 41 PM](https://user-images.githubusercontent.com/106930430/172210348-6d0796d1-1533-4296-964c-8868aacc5228.png)

**Comment by czczup** [comment]
> Says CUDA not available. I know PyTorch recently released support for training on M1 Macs, but do you think the problem could be M1 related?
> 
> ![Screen Shot 2022-06-06 at 1 07 41 PM](https://user-images.githubusercontent.com/106930430/172210348-6d0796d1-1533-4296-964c-8868aacc5228.png)

This code requires an Nvidia GPU.

**Comment by wesley960** [comment]
Ah I see, alright thank you!
