### ISSUE TITLE
dist_test.sh: 8: dist_test.sh: Bad substitution

### ISSUE THREAD

**Issue by leetesua** [czczup/ViT-Adapter#40]
here is my command: 
(vit_adapter) lidexuan@aa-SYS-4029GP-TRT:/data/lidexuan/ViT-Adapter/detection$ sh dist_test.sh configs/htc++/htc++_beit_adapter_large_fpn_3x_coco.py htc++_beit_adapter_large_fpn_3x_coco.pth.tar 8 --eval bbox segm
dist_test.sh: 8: dist_test.sh: Bad substitution

any idea?

**Comment by duanduanduanyuchen** [comment]
> here is my command: (vit_adapter) lidexuan@aa-SYS-4029GP-TRT:/data/lidexuan/ViT-Adapter/detection$ sh dist_test.sh configs/htc++/htc++_beit_adapter_large_fpn_3x_coco.py htc++_beit_adapter_large_fpn_3x_coco.pth.tar 8 --eval bbox segm dist_test.sh: 8: dist_test.sh: Bad substitution
> 
> any idea?

Hi, the parameter '8' means to use 8 gpus in your program. Does your machine have 8 gpus? Or do you have more error information?

**Comment by czczup** [comment]
> here is my command: (vit_adapter) lidexuan@aa-SYS-4029GP-TRT:/data/lidexuan/ViT-Adapter/detection$ sh dist_test.sh configs/htc++/htc++_beit_adapter_large_fpn_3x_coco.py htc++_beit_adapter_large_fpn_3x_coco.pth.tar 8 --eval bbox segm dist_test.sh: 8: dist_test.sh: Bad substitution
> 
> any idea?
Hi, you can use `bash` instead of `sh`.
