### ISSUE TITLE
how to get pth.tar file after trainning own dataset?

### ISSUE THREAD

**Issue by StawEndl** [czczup/ViT-Adapter#43]
hi, i trained on my own dataset, and get pth files, but image_demo.py need a pth.tar file as weight, so how to get the pth.tar file by pth file? can i just run "tar -cvf iter_xxxx.pth.tar iter_xxxx.pth"?

**Comment by czczup** [comment]
Hi, give image_demo.py a .pth is ok

**Comment by StawEndl** [comment]
> Hi, giving `image_demo.py` a `.pth` is ok.

you mean "python image_demo.py  xxxxade20k_ss.py iter_xxxx.pth  ADE_val_00000591.jpg  --palette ade20k"??

**Comment by czczup** [comment]
> > Hi, giving `image_demo.py` a `.pth` is ok.
> 
> you mean "python image_demo.py xxxxade20k_ss.py iter_xxxx.pth ADE_val_00000591.jpg --palette ade20k"??

Yes
