### ISSUE TITLE
Is the ViT backbone frozen? 

### ISSUE THREAD

**Issue by bryanyzhu** [czczup/ViT-Adapter#5]
In some adapter literature, the backbone is frozen, I just want to double check if the ViT backbone here is frozen. It seems from the figure that ViT backbone is in grey color, which might indicate freezing? But I didn't find corresponding description in the paper, thank you.

**Comment by czczup** [comment]
Thanks for your attention, in our vit-adapter, all parameters need to be fine-tuned for downstream tasks.
