### ISSUE TITLE
How to use Mask2Former for real time ? 

### ISSUE THREAD

**Issue by ashishML** [czczup/ViT-Adapter#54]
Mask2Former with Vit-L is too slow for inference. What is the best way to speed it up ??

**Comment by ashishML** [comment]
Also should this be deployed using TorchServe ???

**Comment by czczup** [comment]
Hi, you can try these [tools](https://github.com/open-mmlab/mmdetection/tree/master/tools/deployment) provided by mmdetection official, to convert the model to tensorrt or torchserve.

**Comment by ashishML** [comment]
Thanks. Will try this.

**Comment by WilsonAir** [comment]
I am curious about the time consuming after deploy with TorchServer, and dose it realize realtime inference? Could you please share the performance results with us?
