### ISSUE TITLE
The paper and the code seem to be inconsistent

### ISSUE THREAD

**Issue by lingziqiang** [czczup/ViT-Adapter#55]
In the structure of the model, the paper and the code seem to be inconsistent. There are two inconsistencies:

1) In this paper, the input of Block is a combination of the output of Injector and Patch Embedding. However, in the code, there is only the output of Injector;

2) In this paper, the input of the Extractor is the fusion of the output of Block and Injector, while in the code, it is the fusion of SPM and Block output.

**Comment by czczup** [comment]
Hi, thanks for your attention. Let me give some explanations.

1. In this paper, the input of Block is a combination of the output of Injector and Patch Embedding. However, in the code, there is only the output of Injector;

A1: There may be some confusion. In the code, the input of the first ViT Block is an addition of the output of Injector and Patch Embedding, as you can see in line#145 and line#178 of this [file](https://github.com/czczup/ViT-Adapter/blob/main/detection/mmdet_custom/models/backbones/adapter_modules.py). For the first ViT block, the query in the Injector is the feature comes from Patch Embedding, while `attn` denotes the output of cross attention. We add these two features as the input of ViT Block.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/23737120/203216863-8ecc4a58-6ba9-49bd-8774-a528f082d771.png">

**Comment by czczup** [comment]
2. In this paper, the input of the Extractor is the fusion of the output of Block and Injector, while in the code, it is the fusion of SPM and Block output.

A2: In the code, the input of the Extractor is the fusion of the output of Block and last Extractor, as you can see in this figure,  Injector pass the $F_{\rm sp}^i$, so it's actually the output of the previous Extractor.


<img width="583" alt="image" src="https://user-images.githubusercontent.com/23737120/203218441-84307e22-ec71-4a61-a9dc-8c611dcc5f90.png">


`x` is the output of ViT Block.
`c` is the output of last Extractor.


<img width="586" alt="image" src="https://user-images.githubusercontent.com/23737120/203217599-4ae9cc01-b114-43a8-ad1f-730eb645a904.png">

**Comment by lingziqiang** [comment]
I see. Thank you for your answer.
&nbsp;


凌自强
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhe ***@***.***&gt;; 
发送时间: 2022年11月22日(星期二) 中午12:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [czczup/ViT-Adapter] The paper and the code seem to be inconsistent (Issue #55)





  
In this paper, the input of the Extractor is the fusion of the output of Block and Injector, while in the code, it is the fusion of SPM and Block output.
  
A2: In the code, the input of the Extractor is the fusion of the output of Block and last Extractor, as you can see in this figure,  Injector pass the $F_{\rm sp}^i$, so it's actually the output of the previous Extractor.
 

 
x is the output of ViT Block.
 c is the output of last Extractor.
