### ISSUE TITLE
The evaluation shows NaN except for the 1st index.

### ISSUE THREAD

**Issue by sasin1996** [czczup/ViT-Adapter#56]
Do you know why the bg class (background) is show nan? 
Sometimes, when I swap the bg class to the 1st index the corrosion usually displays nan stead of it.

![202412668-763edbaf-2741-4265-a01c-21033dee9acc](https://user-images.githubusercontent.com/75520236/203507203-dbcff479-3d87-4cac-98c4-5b8d1b52da15.png)

**Comment by czczup** [comment]
Hi, may I ask if your background is labeled as 0 in the groundtruth? And the foreground category is labeled as 1?

**Comment by sasin1996** [comment]
Thank you very very much, Your suggestion works for me. :))

**Comment by czczup** [comment]
> Thank you very very much, Your suggestion works for me. :))

It's a pleasure to help you.
