### ISSUE TITLE
Error(s) in loading state_dict 

### ISSUE THREAD

**Issue by zhu-gl-ux** [czczup/ViT-Adapter#57]
Hello, when I use beitadapter to test, there is an error in weight loading. How can I solve it?
error is fellow：
RuntimeError: Error(s) in loading state_dict for BeiTAdapter_L:
        Missing key(s) in state_dict: "backbone.blocks.0.attn.relative_position_index", "backbone.blocks.1.attn.relative_position_index", "backbone.blocks.2.attn.relative_position_index", "backbone.blocks.3.attn.relative_position_index", "backbone.blocks.4.attn.relative_position_index", "backbone.blocks.5.attn.relative_position_index", "backbone.blocks.6.attn.relative_position_index", "backbone.blocks.7.attn.relative_position_index", "backbone.blocks.8.attn.relative_position_index", "backbone.blocks.9.attn.relative_position_index", "backbone.blocks.10.attn.relative_position_index", "backbone.blocks.11.attn.relative_position_index", "backbone.blocks.12.attn.relative_position_index", "backbone.blocks.13.attn.relative_position_index", "backbone.blocks.14.attn.relative_position_index", "backbone.blocks.15.attn.relative_position_index", "backbone.blocks.16.attn.relative_position_index", "backbone.blocks.17.attn.relative_position_index", "backbone.blocks.18.attn.relative_position_index", "backbone.blocks.19.attn.relative_position_index", "backbone.blocks.20.attn.relative_position_index", "backbone.blocks.21.attn.relative_position_index", "backbone.blocks.22.attn.relative_position_index", "backbone.blocks.23.attn.relative_position_index".

**Comment by czczup** [comment]
Hey, what's your command to test this model? I noticed that you seem to have some custom code. If you modified some code, please notice that in the `model.load_state_dict()` function, strict should be set to `False`. The missing of these keys is to save disk space and has no influence on model testing.

**Comment by zhu-gl-ux** [comment]
Thanks for your reply, it works！At the same time, thank much for your model weights.
