### ISSUE TITLE
Error in grid_sampler

### ISSUE THREAD

**Issue by thegigasurgeon-attentive** [czczup/ViT-Adapter#6]
Hi. I am using a custom dataset and receiving this error. Used ADE20k dataset and received the same error.

  ```
File "/home/workspace/training/ViT-Adapter/segmentation/mmseg_custom/core/utils/misc.py", line 21, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/workspace/training/ViT-Adapter/segmentation/mmseg_custom/models/decode_heads/mask2former_head.py", line 242, in _get_target_single
    1)).squeeze(1)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mmcv/ops/point_sample.py", line 280, in point_sample
    input, denormalize(points), align_corners=align_corners, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 4011, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected 4D or 5D input and grid with same number of dimensions, but got input with sizes [20, 1, 512, 512, 3] and grid with sizes [20, 12544, 1, 2]
```

**Comment by duanduanduanyuchen** [comment]
> Hi. I am using a custom dataset and receiving this error. Used ADE20k dataset and received the same error.
> 
> ```
> File "/home/workspace/training/ViT-Adapter/segmentation/mmseg_custom/core/utils/misc.py", line 21, in multi_apply
>   return tuple(map(list, zip(*map_results)))
> File "/home/workspace/training/ViT-Adapter/segmentation/mmseg_custom/models/decode_heads/mask2former_head.py", line 242, in _get_target_single
>   1)).squeeze(1)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/mmcv/ops/point_sample.py", line 280, in point_sample
>   input, denormalize(points), align_corners=align_corners, **kwargs)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 4011, in grid_sample
>   return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
> RuntimeError: grid_sampler(): expected 4D or 5D input and grid with same number of dimensions, but got input with sizes [20, 1, 512, 512, 3] and grid with sizes [20, 12544, 1, 2]
> ```

Hi, can you provide your torch/mmseg/mmcv version?

**Comment by thegigasurgeon-attentive** [comment]
python - 3.6.9
torch - 1.10.2+cu113
mmsegmentation - 0.20.2
mmcv-full  - 1.4.2
cuda - 11.3

**Comment by duanduanduanyuchen** [comment]
It seems like your "gt_mask" has a wrong shape. I think you should check the shape of "gt_semantic_seg"(should be (512,512) in your experiment) and make sure "ToMask" operation in `segmentation/mmseg_custom/datasets/pipelines/formatting.py` is in your dataset pipeline.

**Comment by thegigasurgeon-attentive** [comment]
Thanks @duanduanduanyuchen . I just checked, my GTs were RGB instead of grayscale. Converted my annotations from (512,512,3) to (512,512) and it works now.
