### ISSUE TITLE
Using Test.py 

### ISSUE THREAD

**Issue by dhosk22** [czczup/ViT-Adapter#60]
Hi, I have two questions about the test.py file.

1. I'm trying to use test.py in the same way that I got image_demo.py working. I've noticed that test.py doesn't have an image directory argument similar to the 'img' argument in image_demo.py. How should I tell test.py what data to test?

`!CUDA_VISIBLE_DEVICES=0 python test.py \
  /content/ViT-Adapter/segmentation/configs/cityscapes/mask2former_beit_adapter_large_896_80k_cityscapes_ms.py  \
  /content/ViT-Adapter/segmentation/release/mask2former_beit_adapter_large_896_80k_cityscapes.pth.tar  \
  /content/drive/MyDrive/ColabNotebooks/ViT-AdapterContent/dataA/dataA/CameraRGB \`

The 3rd argument is the directory where my data is.  

2. Also I noticed that in the image_demo.py file, there is a --palette argument to choose the segmentation palette, but there isn't in the test.py file. If I added that to test.py, would I easily be able to add custom palettes, specific to the dataset of testing interest?

**Comment by czczup** [comment]
Hi, the `test.py` is a copy of https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py.
You can see the [document](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/inference.md) provided by segmentation for help.
