### ISSUE TITLE
How to use simplecopypaste augments on vit-adapter model?

### ISSUE THREAD

**Issue by Skyninth** [czczup/ViT-Adapter#61]
I try to use simplecopypaste on beitv2 with 4 A30 GPUS, but loss will become nan suddenly.
here is my dataset configs:

dataset_type = 'CocoDataset'
data_root = 'data/bt474_NoOverlap/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

file_client_args = dict(backend='disk')
load_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=file_client_args),
    dict(type='InstaBoost',
         action_candidate=('normal', 'horizontal', 'skip'),
         action_prob=(1, 0, 0),
         scale=(0.8, 1.2),
         dx=15,
         dy=15,
         theta=(-1, 1),
         color_prob=0.5,
         hflag=False,
         aug_ratio=0.5),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Albu',transforms=[
            dict(type='RandomRotate90', always_apply=False, p=0.5),
            dict(type='RandomBrightnessContrast', brightness_limit=0.2,
                 contrast_limit=0.4, p=0.5),
            dict(type="GaussianBlur", blur_limit=7, p=0.4),
        ],
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap=dict(img='image', gt_bboxes='bboxes', gt_masks='masks'),
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(
        type='Resize',
        img_scale=[(512, 512)],
        ratio_range=(0.8, 1.2),
        multiscale_mode='range',
        keep_ratio=True),
    dict(
        type='RandomCrop',
        crop_type='absolute_range',
        crop_size=(512, 512),
        recompute_bbox=True,
        allow_negative_crop=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1e-2, 1e-2)),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size=(512, 512)),
]

train_pipeline = [
    dict(type='CopyPaste', max_num_pasted=100),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
dataclass = ['cell']
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type='MultiImageMixDataset',
        dataset=dict(
            type=dataset_type,
            ann_file=data_root + 'annotations/livecell_bt474_train.json',
            img_prefix=data_root + 'images/train_val/',
            pipeline=load_pipeline),
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes=dataclass,
        ann_file=data_root + 'annotations/livecell_bt474_val.json',
        img_prefix=data_root + 'images/train_val/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=dataclass,
        ann_file=data_root + 'annotations/livecell_bt474_test.json',
        img_prefix=data_root + 'images/test/',
        pipeline=test_pipeline))
evaluation = dict(metric=['bbox', 'segm'])

beitv2 configs I didn't change.

**Comment by czczup** [comment]
Hi, you could refer to this [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/common/ssj_scp_270k_coco_instance.py) to use simple copy paste in mmdetection.
