### ISSUE TITLE
About window attention

### ISSUE THREAD

**Issue by qyx1121** [czczup/ViT-Adapter#65]
Hi, I noticed that you used the pre-trained parameter to initialize vit, then changed the attention module of 8 vit blocks to window attention, and then finetune it on the downstream task. I would like to ask whether this way of replacing the attention module will lead to the pre-trained knowledge not well transferred to the downstream task?

**Comment by czczup** [comment]
Hello, you can still load all the pre-trained weights after replacing global attention with window attention, because the parameters in the attention module are mainly linear layers.
