### ISSUE TITLE
无法复现cityscapes准确率指标

### ISSUE THREAD

**Issue by zhangsiqiGit** [czczup/ViT-Adapter#68]
Hi，我在尝试复现cityscapes val数据集的mIoU指标，准确率很接近但无法达到report中的84.9。
cmd：
bash dist_test.sh configs/cityscapes/mask2former_beit_adapter_large_896_80k_cityscapes_ss.py released/mask2former_beit_adapter_large_896_80k_mapillary.pth.tar 2 --eval cityscpaes

准确率数值如下：

Class | IoU（Report） | IoU（Test）
-- | -- | --
road | 98.66 | 98.1
sidewalk | 89.05 | 83.5
building | 94.62 | 94.4
wall | 74.36 | 68.9
fence | 73.86 | 66.5
pole | 72.01 | 74.5
Traffic light | 76.87 | 77.6
Traffic sign | 84.44 | 81.9
vegetation | 93.4 | 93.2
terrain | 67.82 | 54.3
sky | 95.81 | 96.2
person | 86.95 | 85.8
rider | 75.15 | 69.9
car | 95.85 | 96.3
truck | 90.99 | 89.5
bus | 94.28 | 94.9
train | 90.05 | 89.2
motorcycle | 76.45 | 72.9
bicycle | 82.88 | 79.9

其中，左侧是mIoU(ss)的report指标84.9，右侧是评估的指标81.4。

请问我需要修改什么地方吗？

**Comment by czczup** [comment]
你好，我看你的命令是在跑测试，那么好像跑错checkpoint文件了。你跑的是mapillary数据集预训练的权重，https://github.com/czczup/ViT-Adapter/releases/download/v0.2.3/mask2former_beit_adapter_large_896_80k_cityscapes.zip 这个才是cityscapes 84.9的权重。

**Comment by zhangsiqiGit** [comment]
> 你好，我看你的命令是在跑测试，那么好像跑错checkpoint文件了。你跑的是mapillary数据集预训练的权重，https://github.com/czczup/ViT-Adapter/releases/download/v0.2.3/mask2former_beit_adapter_large_896_80k_cityscapes.zip 这个才是cityscapes 84.9的权重。

thanks a lot! have a 84.7 mIoU performance.
