### ISSUE TITLE
When I tried to use pretrained backbone it reports error

### ISSUE THREAD

**Issue by gjghs** [czczup/ViT-Adapter#69]
Traceback (most recent call last):
  File "/16TB/code/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/16TB/code/ViT-Adapter/segmentation/mmseg_custom/models/backbones/beit_adapter.py", line 26, in __init__
    super().__init__(init_values=init_values, with_cp=with_cp, *args, **kwargs)
  File "/16TB/code/ViT-Adapter/segmentation/mmseg_custom/models/backbones/base/beit.py", line 344, in __init__
    self.init_weights(pretrained)
  File "/16TB/code/ViT-Adapter/segmentation/mmseg_custom/models/backbones/base/beit.py", line 358, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/16TB/code/ViT-Adapter/segmentation/mmcv_custom/checkpoint.py", line 400, in load_checkpoint
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/16TB/code/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/16TB/code/ViT-Adapter/segmentation/mmseg_custom/models/segmentors/encoder_decoder_mask2former.py", line 34, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/16TB/code/mmsegmentation/mmseg/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/16TB/code/mmcv/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/16TB/code/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/16TB/code/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NotImplementedError: BEiTAdapter: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 216, in <module>
    main()
  File "train.py", line 172, in main
    model = build_segmentor(
  File "/16TB/code/mmsegmentation/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/16TB/code/mmcv/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/16TB/code/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/16TB/code/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NotImplementedError: EncoderDecoderMask2Former: BEiTAdapter:

I've run lines 'ln -s ../detection/ops ./
cd ops & sh make.sh # compile deformable attention'

It seems that segmentor and backbone not registed in mmcv.What should I do

**Comment by czczup** [comment]
Hi, could you provide the config file you used? It seems that you feed a non-square image into BEiT.

**Comment by gjghs** [comment]
> Hi, could you provide the config file you used? It seems that you feed a non-square image into BEiT.

Oh yes, sorry I didn't mention it.I used (720, 1280) as my backbone's img_size param cause its my original image ratio.Does it supports?

**Comment by gjghs** [comment]
> Hi, could you provide the config file you used? It seems that you feed a non-square image into BEiT.

_base_ = [
    '../_base_/models/mask2former_beit_cityscapes.py',
]
num_things_classes = 0
num_stuff_classes = 2
num_classes = num_things_classes + num_stuff_classes
norm_cfg = dict(type='SyncBN', requires_grad=True)
crop_size = (720, 1280)
# pretrained = 'https://conversationhub.blob.core.windows.net/beit-share-public/beit/beit_large_patch16_224_pt22k_ft22k.pth'
pretrained = 'pretrained/beit_large_patch16_224_pt22k_ft22k.pth'
# pretrained = None
model = dict(
    pretrained=pretrained,
    backbone=dict(
        type='BEiTAdapter',
        img_size=crop_size,
        patch_size=16,
        embed_dim=1024,
        depth=24,
        num_heads=16,
        mlp_ratio=4,
        qkv_bias=True,
        use_abs_pos_emb=False,
        use_rel_pos_bias=True,
        init_values=1e-6,
        drop_path_rate=0.3,
        conv_inplane=64,
        n_points=4,
        deform_num_heads=16,
        cffn_ratio=0.25,
        deform_ratio=0.5,
        with_cp=True,  # set with_cp=True to save memory
        interaction_indexes=[[0, 5], [6, 11], [12, 17], [18, 23]],
    ),
    decode_head=dict(
        in_channels=[1024, 1024, 1024, 1024],
        feat_channels=1024,
        out_channels=1024,
        num_queries=100,
        pixel_decoder=dict(
            type='MSDeformAttnPixelDecoder',
            num_outs=3,
            norm_cfg=dict(type='GN', num_groups=32),
            act_cfg=dict(type='ReLU'),
            encoder=dict(
                type='DetrTransformerEncoder',
                num_layers=6,
                transformerlayers=dict(
                    type='BaseTransformerLayer',
                    attn_cfgs=dict(
                        type='MultiScaleDeformableAttention',
                        embed_dims=1024,
                        num_heads=32,
                        num_levels=3,
                        num_points=4,
                        im2col_step=64,
                        dropout=0.0,
                        batch_first=False,
                        norm_cfg=None,
                        init_cfg=None),
                    ffn_cfgs=dict(
                        type='FFN',
                        embed_dims=1024,
                        feedforward_channels=4096,
                        num_fcs=2,
                        ffn_drop=0.0,
                        with_cp=True,  # set with_cp=True to save memory
                        act_cfg=dict(type='ReLU', inplace=True)),
                    operation_order=('self_attn', 'norm', 'ffn', 'norm')),
                init_cfg=None),
            positional_encoding=dict(
                type='SinePositionalEncoding', num_feats=512, normalize=True),
            init_cfg=None),
        positional_encoding=dict(
            type='SinePositionalEncoding', num_feats=512, normalize=True),
        transformer_decoder=dict(
            type='DetrTransformerDecoder',
            return_intermediate=True,
            num_layers=9,
            transformerlayers=dict(
                type='DetrTransformerDecoderLayer',
                attn_cfgs=dict(
                    type='MultiheadAttention',
                    embed_dims=1024,
                    num_heads=32,
                    attn_drop=0.0,
                    proj_drop=0.0,
                    dropout_layer=None,
                    batch_first=False),
                ffn_cfgs=dict(
                    embed_dims=1024,
                    feedforward_channels=4096,
                    num_fcs=2,
                    act_cfg=dict(type='ReLU', inplace=True),
                    ffn_drop=0.0,
                    dropout_layer=None,
                    with_cp=True,  # set with_cp=True to save memory
                    add_identity=True),
                feedforward_channels=4096,
                operation_order=('cross_attn', 'norm', 'self_attn', 'norm',
                                 'ffn', 'norm')),
            init_cfg=None)
    ),
    test_cfg=dict(mode='whole', crop_size=crop_size)
)
# dataset settings
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(1280, 720), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=0),
    dict(type='ToMask'),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg', 'gt_masks', 'gt_labels'])
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1280, 720),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

dataset_type = 'FreeSpaceDataset'
classes = ('background', 'free space')
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        ann_file='/SSD/freespace/train_list.txt',
        classes=classes,
        pipeline=train_pipeline,),
    val=dict(
        type=dataset_type,
        ann_file='/SSD/freespace/val_list.txt',
        classes=classes,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file='/SSD/freespace/val_list.txt',
        classes=classes,
        pipeline=test_pipeline),
    train_dataloader=dict(shuffle=True,),
    )

Here is my model and dataset config

**Comment by czczup** [comment]
This is beacuse BEiT only support square images. One possible solution is set the crop size as (720, 720) and use slide mode in test_cfg.

Besides, I'd like to ask how much GPU memory you have, because it might be out of memory.

**Comment by czczup** [comment]
Since your dataset only has 2 classes, I recommend reducing the width of the head.
Like this:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/23737120/212256898-a31d0a4e-bfb3-42b7-899b-11a1cebe0cfe.png">
<img width="580" alt="image" src="https://user-images.githubusercontent.com/23737120/212257020-65a447cb-b937-4679-aaaa-c2af099f3175.png">

**Comment by gjghs** [comment]
> Since your dataset only has 2 classes, I recommend reducing the width of the head.
> Like this:
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/23737120/212256898-a31d0a4e-bfb3-42b7-899b-11a1cebe0cfe.png">
> <img alt="image" width="580" src="https://user-images.githubusercontent.com/23737120/212257020-65a447cb-b937-4679-aaaa-c2af099f3175.png">

Thanks very much for ur help.My card is 3090.I might need some changes to run it
