### ISSUE TITLE
The dimensions do not broadcast

### ISSUE THREAD

**Issue by rmihaylov** [czczup/ViT-Adapter#7]
Hi, great work! Trying to test it out. Maybe a bug:

<b>Settings</b>
    config: mask2former_beit_adapter_base_512_40k_cocostuff10k_ss.py
    checkpoint: mask2former_beit_adapter_base_512_40k_cocostuff10k.pth.tar

<b>Error</b>
In this line in beit.py:
```
            attn = attn + relative_position_bias.unsqueeze(0)
```
The dimensions do not broadcast.
If one takes an input image 1x3x128x128, then the dimensions are:

```
# attn.shape
# ([1, 12, 65, 65])

# relative_position_bias.unsqueeze(0).shape
# ([1, 12, 1025, 1025])
```

**Comment by czczup** [comment]
> Hi, great work! Trying to test it out. Maybe a bug:
> 
> Settings config: mask2former_beit_adapter_base_512_40k_cocostuff10k_ss.py checkpoint: mask2former_beit_adapter_base_512_40k_cocostuff10k.pth.tar
> 
> Error In this line in beit.py:
> 
> ```
>             attn = attn + relative_position_bias.unsqueeze(0)
> ```
> 
> The dimensions do not broadcast. If one takes an input image 1x3x128x128, then the dimensions are:
> 
> ```
> # attn.shape
> # ([1, 12, 65, 65])
> 
> # relative_position_bias.unsqueeze(0).shape
> # ([1, 12, 1025, 1025])
> ```

Yes, BEiT has a limitation on image resolution. When it is set to `img_size=512`, the input image must be `1x3x512x512`.
It does not support a dynamic resolution (due to its implementation of relative position encoding), one possible way is to pad a 128x128 image to 512x512. Or if all images are 128x128, set `img_size=128`.

**Comment by rmihaylov** [comment]
Thank you for your fast reply. I fixed it in the code like this. Works like charm:

```
attn = attn + tf.expand_dims(relative_position_bias[:,:N,:N], 0)
```

**Comment by paarthmadan29** [comment]
Can you explain your solution in more detail please @rmihaylov . I'm using pytorch.
Thanks
