### ISSUE TITLE
使用 ops/make.sh 编译MSDA时报错

### ISSUE THREAD

**Issue by wuhaozede** [czczup/ViT-Adapter#70]
环境：Win11、CUDA（11.2）、MSVC v141 2017 C++ （14.16）、Python相关库按 detection/README.md 安装成功

执行 nvcc.exe 时报错

错误：
`D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(127): error: identifier "grad_output_n" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: type name is not allowed

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: expected an expression

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "per_sample_loc_size" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "per_attn_weight_size" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "grad_sampling_loc" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: type name is not allowed

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: expected an expression

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "grad_attn_weight" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: type name is not allowed

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: expected an expression

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: no instance of function template "ms_deformable_col2im_cuda" matches the argument list
            argument types are: (c10::cuda::CUDAStream, <error-type>, double *, int64_t *, int64_t *, <error-type>, <error-type>, const int, const int, const int, const int, const int, const int, const int, double *, <error-type>, <error-type>)

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: type name is not allowed

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: expected an expression

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "per_sample_loc_size" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "per_attn_weight_size" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "grad_sampling_loc" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: type name is not allowed

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: expected an expression

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: identifier "grad_attn_weight" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: type name is not allowed

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: expected an expression

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(128): error: no instance of function template "ms_deformable_col2im_cuda" matches the argument list
            argument types are: (c10::cuda::CUDAStream, <error-type>, float *, int64_t *, int64_t *, <error-type>, <error-type>, const int, const int, const int, const int, const int, const int, const int, float *, <error-type>, <error-type>)

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(145): error: identifier "grad_sampling_loc" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(145): error: identifier "grad_attn_weight" is undefined

D:/A/name/ViT-Adapter-main/detection/ops/src\cuda/ms_deform_im2col_cuda.cuh(258): warning: variable "q_col" was declared but never referenced
          detected during:
            instantiation of "void ms_deformable_im2col_gpu_kernel(int, const scalar_t *, const int64_t *, const int64_t *, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int, scalar_t *) [with scalar_t=double]"
(943): here
            instantiation of "void ms_deformable_im2col_cuda(cudaStream_t, const scalar_t *, const int64_t *, const int64_t *, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int, scalar_t *) [with scalar_t=double]"
D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(64): here

D:/A/name/ViT-Adapter-main/detection/ops/src\cuda/ms_deform_im2col_cuda.cuh(258): warning: variable "q_col" was declared but never referenced
          detected during:
            instantiation of "void ms_deformable_im2col_gpu_kernel(int, const scalar_t *, const int64_t *, const int64_t *, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int, scalar_t *) [with scalar_t=float]"
(943): here
            instantiation of "void ms_deformable_im2col_cuda(cudaStream_t, const scalar_t *, const int64_t *, const int64_t *, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int, scalar_t *) [with scalar_t=float]"
D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu(64): here

25 errors detected in the compilation of "D:/A/name/ViT-Adapter-main/detection/ops/src/cuda/ms_deform_attn_cuda.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin\\nvcc.exe' failed with exit status 1`

**Comment by wuhaozede** [comment]
补充说明：环境可能存在一定问题，我电脑上同时安装了最新的 **MSVC v143 2022 C++** 与 **MSVC v141 2017 C++ （14.16）**

在编译前报错：

cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。

但是在执行 nvcc.exe 时有：

-ID:\Python\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\**14.16.27023**\include"

**Comment by czczup** [comment]
> 补充说明：环境可能存在一定问题，我电脑上同时安装了最新的 **MSVC v143 2022 C++** 与 **MSVC v141 2017 C++ （14.16）**
> 
> 在编译前报错：
> 
> cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
> 
> 但是在执行 nvcc.exe 时有：
> 
> -ID:\Python\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.16.27023\include"

我没有尝试过在windows系统下编译，可能存在兼容问题，还是比较推荐在linux系统里运行。
windows的一种可能的解决方案是采用mmcv里预编译好的deformable attention, 可以参考[issue#41](https://github.com/czczup/ViT-Adapter/issues/41)。

**Comment by wuhaozede** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wuhaozede** [comment]
好的，感谢您的回复！

**Comment by ChangWenYu** [comment]
See?Almost all the error are reported on the same line in ms_deform_attn_cuda.cu.This is because the operation of breaking a line differs between linux and windows(Windows is CRLF.Linux is LF).So the compiler consider multi-lines as a single line on windows(because the source code is created on linux).Using notepad++ to scan and replace all the LF with CRLF solved the issue.

**Comment by duckfen** [comment]
> See?Almost all the error are reported on the same line in ms_deform_attn_cuda.cu.This is because the operation of breaking a line differs between linux and windows(Windows is CRLF.Linux is LF).So the compiler consider multi-lines as a single line on windows(because the source code is created on linux).Using notepad++ to scan and replace all the LF with CRLF solved the issue.

Thanks for your help. After changing the.cu and.cuh files to windows format, you can compile msda
