### ISSUE TITLE
missing keys in source state_dict error 

### ISSUE THREAD

**Issue by MartaFdez97** [czczup/ViT-Adapter#74]
Hello, 
I am trying to run this: 

CUDA_VISIBLE_DEVICES=0 python image_demo.py \
  configs/ade20k/mask2former_beit_adapter_large_896_80k_ade20k_ss.py  \
  released/mask2former_beit_adapter_large_896_80k_ade20k.pth.tar  \
  data/ade/ADEChallengeData2016/images/validation/ADE_val_00000591.jpg \
  --palette ade20k 

but I obtain this error: 

load checkpoint from local path: ./released/mask2former_beitv2_adapter_large_896_80k_ade20k.pth
The model and loaded state dict do not match exactly

missing keys in source state_dict: backbone.blocks.0.attn.relative_position_index, backbone.blocks.1.attn.relative_position_index, backbone.blocks.2.attn.relative_position_index, backbone.blocks.3.attn.relative_position_index, backbone.blocks.4.attn.relative_position_index, backbone.blocks.5.attn.relative_position_index, backbone.blocks.6.attn.relative_position_index, backbone.blocks.7.attn.relative_position_index, backbone.blocks.8.attn.relative_position_index, backbone.blocks.9.attn.relative_position_index, backbone.blocks.10.attn.relative_position_index, backbone.blocks.11.attn.relative_position_index, backbone.blocks.12.attn.relative_position_index, backbone.blocks.13.attn.relative_position_index, backbone.blocks.14.attn.relative_position_index, backbone.blocks.15.attn.relative_position_index, backbone.blocks.16.attn.relative_position_index, backbone.blocks.17.attn.relative_position_index, backbone.blocks.18.attn.relative_position_index, backbone.blocks.19.attn.relative_position_index, backbone.blocks.20.attn.relative_position_index, backbone.blocks.21.attn.relative_position_index, backbone.blocks.22.attn.relative_position_index, backbone.blocks.23.attn.relative_position_index

How can I solve it? 

Thank you in advance

**Comment by czczup** [comment]
Hi, this warning can be ignored. The relative_position_index will be automatically generated during the initialization of the model. We remove them from the checkpoint to reduce the file size.

**Comment by MartaFdez97** [comment]
Okay, thanks! The program stops with that error. How can I ignore it?

**Comment by MartaFdez97** [comment]
Great, thank you very much!

**Comment by studentWUR** [comment]
> Hi, this warning can be ignored. The relative_position_index will be automatically generated during the initialization of the model. We remove them from the checkpoint to reduce the file size.

Does this also holds for the blocks.0.attn.relative_position_bias_table?
