### ISSUE TITLE
Usage of _delete_ parameter

### ISSUE THREAD

**Issue by DianCh** [czczup/ViT-Adapter#75]
Hi, thank you for releasing this wonderful work! I have a quick question: there is a `_delete_=True` field in the configs for ViT-Adapter-B but not for the other sizes - what does this parameter do?

**Comment by czczup** [comment]
> Hi, thank you for releasing this wonderful work! I have a quick question: there is a `_delete_=True` field in the configs for ViT-Adapter-B but not for the other sizes - what does this parameter do?

Hi~, this parameter is used to delete the default settings in the `_base_` files,
such as:
```
_base_ = [
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]
```

**Comment by DianCh** [comment]
@czczup Thank you for the reply! Does this deleting feature come with the original mmcv, or the customized mmcv from this repo? I wonder if need extra engineering if I directly copy-paste these model definitions in my project (using mmdet)

**Comment by czczup** [comment]
> @czczup Thank you for the reply! Does this deleting feature come with the original mmcv, or the customized mmcv from this repo? I wonder if need extra engineering if I directly copy-paste these model definitions in my project (using mmdet)

It's the original feature of mmcv.

**Comment by DianCh** [comment]
Thank you! I'm closing this.
