### ISSUE TITLE
Will you provide vit-T pretrained model?

### ISSUE THREAD

**Issue by guwen007** [czczup/ViT-Adapter#8]

**Comment by guwen007** [comment]
Hi, thank you for your excellent work.
I found that you just provide base and large pretrained model. But i want use the tiny model for small dataset, will you provide tiny pretrained?

**Comment by czczup** [comment]
> Hi, thank you for your excellent work. I found that you just provide base and large pretrained model. But i want use the tiny model for small dataset, will you provide tiny pretrained?
Yes, I have this plan, probably around the end of the week.
