### ISSUE TITLE
Why can't output the painted images when evaluation?

### ISSUE THREAD

**Issue by Weijingmin2000** [czczup/ViT-Adapter#84]
Hi, Thanks for your awesome work first!

I have created folders 'eval/metrics' and ' eval/results' under the 'detection' folder.

When I tried to evaluate the coco2017-val, I found that I could run the test code and save the metrics JSON file under 'eval/metrics'. However, I cannot save the painted images under 'eval/results' or show the results. The shell code I use is as below:

```shell
sh dist_test.sh configs/htc++/htc++_beit_adapter_large_fpn_3x_coco.py checkpoint/htc++_beit_adapter_large_fpn_3x_coco.pth.tar 4 --work-dir eval/metrics --eval bbox segm --show-dir eval/results

sh dist_test.sh configs/htc++/htc++_beit_adapter_large_fpn_3x_coco.py checkpoint/htc++_beit_adapter_large_fpn_3x_coco.pth.tar 4 --work-dir eval/metrics --eval bbox segm --show
```

I've noticed that in test.py 223-243 lines, you implement the saving method for --out, --format_only and --eval (--work-dir). But I haven't found an implementation for --show and --show-dir. I'm not sure if it's my own problem.

Looking forward to your reply!

**Comment by czczup** [comment]
Hi, the `--show-dir` option only works when using a single GPU. In other words, you should use `python test.py` rather than `sh dist_test.sh`. You can check the document of `mmdetection` for more details.

**Comment by Weijingmin2000** [comment]
Thanks for your help!
