### ISSUE TITLE
Is there a pre-trained vit-Adapter model?

### ISSUE THREAD

**Issue by ilplmm123** [czczup/ViT-Adapter#89]
This work is amazing! But I can not train this model by myself. So Is there a pre-trained Vit-Adapter backbone model?

**Comment by czczup** [comment]
Hi, the pretrained models are provided in the readme of each task.
Detection: https://github.com/czczup/ViT-Adapter/tree/main/detection
Segmentation: https://github.com/czczup/ViT-Adapter/tree/main/segmentation
