### ISSUE TITLE
ImportError: _ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by zwvilliz** [czczup/ViT-Adapter#9]
Hi.Thank you for sharing your work.
But,I followed the steps of usage, but got this error, what should I do?
![2022-06-15 14-51-04屏幕截图](https://user-images.githubusercontent.com/42067161/173761573-43469808-abb3-4a98-a80d-2526ed507c3a.png)

**Comment by duanduanduanyuchen** [comment]
> Hi.Thank you for sharing your work. But,I followed the steps of usage, but got this error, what should I do? ![2022-06-15 14-51-04屏幕截图](https://user-images.githubusercontent.com/42067161/173761573-43469808-abb3-4a98-a80d-2526ed507c3a.png)

Hi! Maybe you should check if the version of your mmcv-full/mmdet/mmseg version, your python/pytorch, your cuda match. If you are not sure, you can follow the doc here: [https://mmcv.readthedocs.io/en/latest/get_started/installation.html](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)
