### ISSUE TITLE
poor performance with DINO V2 pre-trained backbone

### ISSUE THREAD

**Issue by HosseinSheikhi** [czczup/ViT-Adapter#95]
I'm curious to know if you have attempted to use the DINO V2 pre-trained ViT for detection or segmentation tasks. I encountered significantly lower performance with this model compared to other pre-trained models.

**Comment by czczup** [comment]
Hi, thanks for your feedback. I will support recent state-of-the-art pre-training models (including DINO V2 and EVA) after the time of the NeurIPS deadline.

**Comment by HosseinSheikhi** [comment]
it was due to layer scaling module in DINOv2 ViT. It should not be None.

**Comment by sirius-ai** [comment]
hi, @HosseinSheikhi , I am use dinov2 pretrained backbone to do the down stream task like panoptic segmentation, even if 
 I use layer scale module in dinov2, but the performance is not good as beitv2, are you final training results outperform the release beitv2-large?

**Comment by czczup** [comment]
I have added support for dinov2 pre-training in the dinov2 branch, but this is experimental, and it will take some time to check whether the performance is normal.
